<legend class="legend"><span><?php /* @escapeNotVerified */
        echo __('Acceptance of use of personal data') ?></span>
</legend>
<div class="field">
    According to the General Personal Data Protection Law (LGPD), in order for your personal data to be safe and to be used only for the benefits you want, you must consent to their use by clicking below.
</div>

<div class="field required">
    <input type="radio" name="dataPrivacy" id="dataPrivacy" value="true" data-validate="{required:true}">
    <label for="data" class="label">
        <span><?php /* @escapeNotVerified */
            echo __('I accept use of my data'); ?>
        </span>
    </label>
</div>
<hr/>
<div class="field">
    You can change your choices at any time under <b>Data Privacy</b> in your account settings.
</div>
